nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ~/Web:/datas/wwwroot
      - ~/Dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/Dockerfiles/nginx/php.conf:/etc/nginx/php.conf
      - ~/Dockerfiles/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ~/Dockerfiles/nginx/log:/datas/log/nginx

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "redis"
      - "mysql"
    volumes:
      - ~/Dockerfiles/php/php.ini:/usr/local/etc/php/php.ini
      - ~/Dockerfiles/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ~/Dockerfiles/php/log:/datas/log/php
      - ~/Web:/datas/wwwroot
    extra_hosts:
      test_db: 0.0.0.2 
      j.jikexueyuan.com: 0.0.0.0
      yingxiao.jikexueyuan.com: 0.0.0.2
      info.service.jkxy.com: 0.0.0.2
      wechat.service.jkxy.com: 1.0.1.2

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/Dockerfiles/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : 123456789

redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ~/Dockerfiles/redis/redis.conf:/usr/local/etc/redis.conf
      - ~/Dockerfiles/redis/data:/datas/redis
